### ISSUE TITLE
LocationInfo should contain byte offsets 

### ISSUE THREAD

**Issue by pixelami** [inikulin/parse5#103]
When using the SAXParser it would be very useful if the LocationInfo contained `startByteOffset` and `endByteOffset`.

Currently the `startOffset` and `endOffset` represent character positions rather than byte positions which means that trying to use the `startOffset` to access a specific portion of some large HTML file will not work if the HTML contains multibyte characters.

The `startOffset` and `endOffset` will work if the whole source HTML content is read and converted from a Buffer to a String but this kind of defeats the purpose of a SAXParser. 

Having `startByteOffset` and `startByteOffset` will allow this kind of thing....
```
var startByteOffset = 192567;
var endByteOffset = 201154;
var stream = fs.createReadStream(htmlPath, {start:startByteOffset, end:endByteOffset});
```

**Comment by inikulin** [comment]
Yes, parse5 operates with UTF8 code points. It doesn't expect any other encoding as the input. To achieve suggested functionality it should perform decoding of the incoming byte stream as well (ideally, it will require some sophisticated implementation of the decoder that will be able to store code-point-to-byte position information to get location info in one pass). This task, however, is out of the context of this project, since It's possible to built standalone encoder and feed it's result to the parse5, then transform parse5 locations to the byte position.
