### ISSUE TITLE
Seems to parse <template><td></td><tr></tr></template> wrong?

### ISSUE THREAD

**Issue by domenic** [inikulin/parse5#108]
Or maybe it's jsdom's fault? When I run this through jsdom, the node tree gets constructed without the tr.

**Comment by inikulin** [comment]
`<template>` adjusts it's parsing mode by the first start tag in it. In our case it's `<td>`, which means that parser will be switched to the `in row` parsing mode. Since rows in rows are not allowed, following `<tr>` will be omitted. 

E.g. Chrome's output:
![image](https://cloud.githubusercontent.com/assets/453071/13422392/85140158-dfa5-11e5-82c0-e2483e88e461.png)

**Comment by domenic** [comment]
Hmm. I can no longer reproduce my result from last night where I could swear I got Firefox to find the tr. Weird! Thanks for setting me straight.

**Comment by inikulin** [comment]
Maybe you've got a typo in `<template>`? Seems like it's FF bug (IE and Chrome correctly ignores `<tr>` and `<td>`):
![image](https://cloud.githubusercontent.com/assets/453071/13427332/5a972224-dfc4-11e5-951f-cf990ff28a60.png)
