### ISSUE TITLE
loc.attrs has incorrect keys for svg prefixed elements

### ISSUE THREAD

**Issue by MeirionHughes** [inikulin/parse5#149]
Someone PRed a fix for my project that dealt with parse5's change for prefixed attributes. i.e. xlink:href is now `{name:"href", prefix:"xlink"}`. Problem is, the attribute key is down in the loc.attrs as the old style. 

so you have to do something like this to get the attr location: 
```
// for example in svg `<use xlink:href="icons.svg#some_selector">`
attrLoc = loc.attrs[x.prefix + ":" + x.name];
```

**Comment by inikulin** [comment]
Hi!

This is a by design behavior. parse5 has different tree adapters which can produce different tree formats. Default tree adapter was designed to get best performance for the parsing algorithm, that's why attributes presented as array there. Then you parse HTML document, more likely you will like to get it parsed ASAP and you don't care much about fast attributes lookup (in common case). Meanwhile, the only thing that you can do with location info is to perform lookup, that's why lookup table fits better there. And, therefore, for obvious reason location info for attributes has prefixed keys. Yes, this leads for API inconsistency, but this inconsistency appears only for default adapter and was introduced for good reasons.
