### ISSUE TITLE
No location info for inline elements containing block elements

### ISSUE THREAD

**Issue by stevenvachon** [inikulin/parse5#197]
```js
const html = `<a href="#"><p></a>`;
const document = require("parse5").parse(html, { locationInfo:true });

document.childNodes[0].childNodes[1].childNodes[0].__location;
//-> { line:1, col:7, startOffset:6, endOffset:25, ... }

document.childNodes[0].childNodes[1].childNodes[1].childNodes[0].__location;
//-> undefined
```

**Comment by inikulin** [comment]
Congratulations, you've hit the darkest corner in the HTML parsing that is the [Adoption Agency Algorithm](https://html.spec.whatwg.org/multipage/syntax.html#adoption-agency-algorithm). 
Consider the following markup `<a>X<p>Y</a>` (it's a bit modified version of your markup with text nodes added for clarity), here is how it will be parsed:
![image](https://cloud.githubusercontent.com/assets/453071/26523057/b31d3670-4316-11e7-987d-f33c05472a15.png)

Parser encounters `a` element that is "split" by `p` element. `a` can't contain `p` element since the former is a block element, therefore it "squeezes out" `p` out of the `a` element. However, according to the markup part of the `p` content was also in the `a` element content. Thus, to preserve semantics and styling parser creates an additional **fake** `a` element (with the same attributes as the original `a` element) inside `p` element that incapsulates content that was previously in both elements.

And here we finally come to our issue: the element whose location you try to obtain is that **fake** `a` element. It doesn't exists in the markup, hence it doesn't have any location. However, the original `a` element (i.e. `document.childNodes[0].childNodes[1].childNodes[0]`) has location as seen from your example.

To conclude it's a by design behavior: we don't add location for the nodes that are not present in the markup, which IMHO makes perfect sense.

**Comment by stevenvachon** [comment]
Thank you. Perhaps we should mention this algorithm in the documentation as an example of when `__location` will be `undefined`. Also, the documentation describes its value as "null", which isn't strictly accurate.

**Comment by inikulin** [comment]
@stevenvachon Would love to accept PR for this
