### ISSUE TITLE
Unexpected serialization of document fragments

### ISSUE THREAD

**Issue by christophercrouzet** [inikulin/parse5#199]
Hello!

I am having troubles serializing a simple tree with nested document fragments, see below:

```js
#!/usr/bin/env node

const parse5 = require('parse5');
const tree = require('parse5').treeAdapters.default;

const NS_URI = 'http://www.w3.org/1999/xhtml';

const MAKE_IT_WORK = false;


const rootNode = tree.createDocumentFragment();
const divNode = tree.createElement('div', NS_URI, []);
const componentNode = tree.createDocumentFragment();
const imgNode = tree.createElement('img', NS_URI, [
  { name: 'src', value: 'image.jpg' },
  { name: 'alt', value: 'my image' },
]);

if (MAKE_IT_WORK === false) {
  tree.appendChild(rootNode, divNode);
  tree.appendChild(divNode, componentNode);
  tree.appendChild(componentNode, imgNode);
} else {
  tree.appendChild(rootNode, divNode);
  tree.appendChild(divNode, imgNode);
}

const html = parse5.serialize(rootNode);
console.log(html);
```

When the variable `MAKE_IT_WORK` is set to `true`, the output reads `<div><img src="image.jpg" alt="my image"></div>` as intended, but otherwise the `img` element is stripped out and only the parent `div` is outputted: `<div></div>`.

Nothing related to this caught my eye in the [Serializing HTML fragments](https://html.spec.whatwg.org/multipage/parsing.html#serialising-html-fragments) section from the HTML spec but then I'm absolutely not familiar with it. Is this an expected behaviour?

**Comment by inikulin** [comment]
The issue is that parse5 tree adapters are not general purpose DOM manipulation libraries. Their primary purpose is to provide a minimal low-level abstraction layer to parser that will allow it to work with a particular abstract syntax tree format. Thus, in this particular case, `appendNode` doesn't expand fragment's child nodes (like full-featured DOM does), it just inserts the fragment node into the tree. Therefore, serializer doesn't serialize this fragment, since fragments are only valid as tree roots or `<template>` content, i.e. you have malformed AST. 

I can suggest you to use [jsdom](https://github.com/tmpvar/jsdom) or [cheerio v1.0-rc1](https://github.com/cheeriojs/cheerio/pull/985#issuecomment-304476652), which use parse5 under the hood for the parsing and serialization purposes, but provide high-level API for such a DOM manipulation tasks.

**Comment by christophercrouzet** [comment]
I see, thanks for the explanation!
