### ISSUE TITLE
Get raw casing of tokens through parser

### ISSUE THREAD

**Issue by kopelli** [inikulin/parse5#214]
I'm trying to do some code linting using parse5, but I've found a use case that I'm not sure it currently supports. Can I get the actual casing of the tokens in addition to (rather than instead of) the lowercase naming?

For example
```html
<Button onClick="return false;">
```
returns `button` and `onclick` rather than `Button` and `onClick`.

Glancing through https://github.com/inikulin/parse5/blob/master/lib/tokenizer/index.js it looks like the codepoints are always lowercased.

**Comment by inikulin** [comment]
HTML spec requires to lowercase tag names and attribute names (with some exceptions for foreign content). However, you can workaround it using location info API and checking source attribute string. Also, AST alone is not sufficient to perform HTML linting, since parser already performs corrections in case of invalid markup. However, AST+location information should work fine.

**Comment by kopelli** [comment]
That makes sense. Was hoping to avoid traversing the content multiple times, but seems unavoidable.
