### ISSUE TITLE
Why not support TreeAdapter.createTextNode?

### ISSUE THREAD

**Issue by panlina** [inikulin/parse5#228]
I'm writing a custom `TreeAdapter`. I want to keep the default implementation, but to add additional properties to node objects. I'm doing well with element nodes by deriving from `treeAdapters.default` and override `TreeAdapter.createElement`, but I can't do the same to text nodes, because there isn't a `TreeAdapter.createTextNode`.
Maybe the reason is that the parser does not directly call `createTextNode`--instead it calls `insertText` and `insertTextBefore`, but I think it'll be easier for people to create `TreeAdapter`s based on existing ones if `createTextNode` is exposed thru the interface.
How do you think?

**Comment by inikulin** [comment]
Hi,

> Maybe the reason is that the parser does not directly call createTextNode--instead it calls insertText and insertTextBefore

That's correct. The reason is that `treeAdapter` is a minimal set of API required by parse5 to perform parsing and not a general purpose DOM manipulation utility belt. 

If you want to manipulate parse5 AST I can suggest you to try https://github.com/Polymer/dom5 or https://github.com/webdeps/parse5-utils
