### ISSUE TITLE
Incorrect image element tag parsing

### ISSUE THREAD

**Issue by Farfurix** [inikulin/parse5#243]
More information in hammerhead context: https://github.com/DevExpress/testcafe-hammerhead/issues/1541

Simple page to process (```<image>``` without ```<svg>``` parent tag):
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<body>
<image id="exp-svg-img-el-1" xmlns:xlink="http://www.w3.org/1999/xlink"
       xlink:href="https://mdn.mozillademos.org/files/6457/mdn_logo_only_color.png" height="50px" width="50px">
</image>
</body>
</html>
```
**The differences** are only in DevTools:Sources (```<img>``` tag instead of ```<image>```)
Processed:
```html
<img id="exp-svg-img-el-1" xmlns:xlink="http://www.w3.org/1999/xlink"
     xlink:href="https://mdn.mozillademos.org/files/6457/mdn_logo_only_color.png" height="50px" width="50px">
```
Original:
```html
<image id="exp-svg-img-el-1" xmlns:xlink="http://www.w3.org/1999/xlink"
       xlink:href="https://mdn.mozillademos.org/files/6457/mdn_logo_only_color.png" height="50px" width="50px">
</image>
```
lib/parser/index.js:
```javascript
function imageStartTagInBody(p, token) { // token.tagName === 'image'
    token.tagName = $.IMG; // token.tagName === $.IMG === 'img'
    areaStartTagInBody(p, token); // then call p._appendElement(token with 'img' tag , NS.HTML);
}
```

**Comment by RReverser** [comment]
AFAIK that's per spec, <image> in HTML context is just an alias that gets transformed into <img>. Browser will do the same if you open such HTML and check devtools.

**Comment by inikulin** [comment]
Hello, thank you for the issue, but I'm afraid I don't quite understand from the provided info what you find incorrect in parse5 behavior.

My only assumption is that replacement of `<image>` with `<img>` has confused you. If so, I can assure you that this behavior is per-specification and implemented in all modern browsers.

I'll close this issue due to insufficient information. Once you provide more info, I will be happy to reopen.
