### ISSUE TITLE
Provide DOM-element source code location information

### ISSUE THREAD

**Issue by cvrebert** [inikulin/parse5#30]
It would be great if parse5 supported the `startIndex` property of htmlparser2's DOM.
See https://github.com/fb55/domhandler#option-withstartindices for a description.
It's very useful for e.g. lint tools that want to point out the source code locations of DOM elements.

**Comment by angelozerr** [comment]
@inikulin I'm very interested too with this feature, because I would like to use SimpleApiParser to retrieve attributes id of an HTML DOM with location.

Indeed, I would like to write a tern plugin http://ternjs.net/doc/demo.html to provide completion, navigation for attributes id for `document.getElementById` inside a JS editor : 

 * test.html : 

```html
<html>
  <script src="test.js" />
  <div id="MyId" ></div>
</html>
```

 * test.js : 

```javascript
var elt = document.getElementById(' // Here Ctrl+Space shows MyId
```

To manage this case, I will load test.html with parse5 to retrieve attributes id.

I need location to support navigation to the HTML file : 

```javascript
var elt = document.getElementById('MyId' // Here Ctrl+click on MyId open the test.html and select MyId.
```
So I need location for this case.

Hope you will have time to support this issue. Thanks!

**Comment by inikulin** [comment]
Hi, guys. 
I will try to get my hands on this as soon as possible. Meanwhile, I have question regarding this functionality: do you need just token's (and appropriate element's in case of DOM-tree parsing) start index or end index is also required?

**Comment by angelozerr** [comment]
> I will try to get my hands on this as soon as possible.

Cool!

> do you need just token's (and appropriate element's in case of DOM-tree parsing) start index or end index is also required?

In my case, I need start/end index for attribute value : 

```html
<div id="MyId" >
              |     |
         start   end 
```

So the token could have this structure : 

```json
{
 "type": "START_TAG_TOKEN",
 "tagName": "div",
 "selfClosing": false,
 "attrs": [
  {
   "name": {
    "content": "id",
    "start": 5,
    "end": 7
   },
   "value": {
    "congtent": "MyId",
    "start": 9,
    "end": 13
   }
  }
 ],
 "start": 0,
 "end": 16
}
```

**Comment by cvrebert** [comment]
I only need the start index for my use case. And I don't need any attribute-level info.

**Comment by inikulin** [comment]
@cvrebert Is it important for you to have the same property naming (`startIndex`) as in htmlparser2? I would like add `__locations` property or something like this for parse5.

**Comment by cvrebert** [comment]
I don't care what you name it, so long as it doesn't overlap with any existing browser DOM property.

**Comment by inikulin** [comment]
Good, thank you.

**Comment by stevenvachon** [comment]
Line/column position for start/end would be awesome as well.

**Comment by angelozerr** [comment]
In my case I need position and not line/column. So I think it should be cool if we could customize that with a boolean option `lineCharPositions`

**Comment by inikulin** [comment]
New version 1.4.0 with this functionality was published to the npm (see [changelog](https://github.com/inikulin/parse5/blob/master/CHANGELOG.md#140)). 

@angelozerr I haven't implemented location info for the attributes in this release, since it's a quite tricky thing to do and I don't have a good idea how to implement it at the moment, so I've created separate issue for this functionality (#43).

**Comment by angelozerr** [comment]
> @angelozerr I haven't implemented location info for the attributes in this release

Thanks for this info. I will wait for this features in a future release, if you can implement it.
