### ISSUE TITLE
Typescript parse5 with WTF typings

### ISSUE THREAD

**Issue by c0ncentus** [inikulin/parse5#344]
hi,

![image](https://user-images.githubusercontent.com/25374826/118117278-b331bd80-b3eb-11eb-8fd2-004bbfcc7fa0.png)

WTF ? 
How do you know if the child have no child  (html string) ? Do you spying my files ? 👎 
# **So I must put "as" everywhere** 
because parser5 say "if you are a child, you have no child", and "if you are a perent then you have no parent". Is why parse5's typings sucks.

![image](https://user-images.githubusercontent.com/25374826/118117671-39e69a80-b3ec-11eb-9091-f582c1ddd498.png)

Okay AST is complex but it's why you should allow one type and make available Parent and Child types

type Node = ParentNode | ChildNode

**Comment by 43081j** [comment]
The AST isn't complex. The types were just badly written and poorly maintained.

I rewrote them mostly from the ground up a while ago so they are much better now but still have some complexities due to the model structure here in parse5.

it isn't as simple as `Node = ParentNode | ChildNode`. 

`childNodes: Node[]` would make you happy but would be incorrect, as a child can't be _any_ node, it can only be those capable of having a parent (a `ChildNode`).

`childNodes: ChildNode[]` is correct but makes you unhappy, as a child can only possibly be a `ChildNode` (i.e. the types of `Node` which have a parent). 

Unfortunately there's no obvious middle ground here. Really its like having `unknown[]`, and up to you to cast as needed.

This ultimately drills down to the fact that the source models are not branded/tagged unions. Types would be much, much nicer if that was the case.

**Comment by Johnrobmiller** [comment]
+1 for this post, new users using parse5 have no way of knowing that they need to explicity cast their node parents/children as the post above suggests.
