### ISSUE TITLE
getTagName in adapters misnamed?

### ISSUE THREAD

**Issue by domenic** [inikulin/parse5#38]
In jsdom 3.0.0, we removed tagName from Node and moved it to Element.

This seems to have cause https://github.com/tmpvar/jsdom/issues/1004. I traced it to the adapter code:

```js
exports.getTagName = function (element) {
  return element.tagName.toLowerCase();
};
```

It seems this gets called with a text node, which no longer has a tagName.

If I switch it to `nodeName`, it seems to work.

Should the adapter hook be renamed to `getNodeName`?

**Comment by inikulin** [comment]
Arggh, I see. Original parse5 treeAdapter doesn't make conversion to the lower case. Therefore it returned `undefined` for the `document` and `documentFragment` nodes. Which worked just fine. In jsdom's treeAdapter it fails by the obvious reason. We shouldn't switch to the `nodeName` here because it will be not quite semantically correct, but it can be easily worked around by checking text node's parent type. Thanks for the report.

**Comment by domenic** [comment]
Hmm so to be clear I found this adapter code *in jsdom*:

https://github.com/tmpvar/jsdom/blob/0da29317ba7893d9d9c44edc5847a981ff7096b5/lib/jsdom/browser/documentAdapter.js#L20-L21

It sounds like I didn't make quite the right modification. What would be the right modification?

- Wait for parse5 to fix itself to not pass non-element nodes, then go back to tagName?
- Check for `element.tagName === undefined` and if so return `undefined` instead of lowercasing?
- Something else?

**Comment by inikulin** [comment]
The best solution will be to wait till I land fix to the parse5 (I'll do it tomorrow or tonight) and rollback to the `tagName`. Checking for `undefined` looks OK for me as well if the original issues should be solved urgently.

**Comment by inikulin** [comment]
I've published update to npm.
