### ISSUE TITLE
Inconsistent handling of nested forms

### ISSUE THREAD

**Issue by ChristianMurphy** [inikulin/parse5#387]
## Steps to reproduce

runnable example: https://stackblitz.com/edit/node-vyajam?file=index.js
parse5 version: 6.0.1

given an html document with nested `<form>` ([invalid in HTML](https://html.spec.whatwg.org/multipage/forms.html#the-form-element))

```html
<!DOCTYPE html>
<html>

<head></head>

<body>
    <form>
        <label>
            <form>
                <label>lorem ipsum</label>
            </form>
            <form>
                <label>lorem ipsum</label>
            </form>
        </label>
    </form>
</body>

</html>
```

parse and serialize the text

```js
const parse5 = require('parse5');

const source = `
<!DOCTYPE html>
<html>

<head></head>

<body>
    <form>
        <label>
            <form>
                <label>lorem ipsum</label>
            </form>
            <form>
                <label>lorem ipsum</label>
            </form>
        </label>
    </form>
</body>

</html>
`;

const originalTree = parse5.parse(source);
const newText = parse5.serialize(originalTree);

console.log(newText);
```

## Expected output

Either keep both nest forms:

```html
<!DOCTYPE html><html><head></head><body>
    <form>
        <label>
            <form>
                <label>lorem ipsum</label>
            </form>
            <form>
                <label>lorem ipsum</label>
            </form>
        </label>
    </form>
</body></html>
```

or remove both nested forms

```html
<!DOCTYPE html><html><head></head><body>
    <form>
        <label>
            <label>lorem ipsum</label>
            <label>lorem ipsum</label>
        </label>
    </form>
</body></html>
```

## Actual output

The first nested form is removed, the second is preserved

```html
<!DOCTYPE html><html><head></head>

<body>
    <form>
        <label>

                <label>lorem ipsum</label>

            <form>
                <label>lorem ipsum</label>
            </form>
        </label></form>
</body></html>
```

## Additional context

Issue was discovered using fuzzing.
A combination of https://github.com/googleprojectzero/domato and https://gitlab.com/gitlab-org/security-products/analyzers/fuzzers/jsfuzz
looking for where parsing, serializing, and re-parsing a document produces different document structure.

**Comment by fictitious** [comment]
This is parsed according to the HTML spec, the browsers do the same thing - if you do `document.write(source)` in the browser console, you will get exactly the same result. [Nested forms is not valid html](https://stackoverflow.com/questions/379610/can-you-nest-html-forms). Invalid html is fixed according to the spec, so parse/serialize round trip in general can not be expected to preserve original html.

There were some discussions in the past about what to do with invalid html - https://github.com/inikulin/parse5/issues/55, https://github.com/inikulin/parse5/issues/180

In this particular case, the spec has a concept of [form element pointer](https://html.spec.whatwg.org/multipage/parsing.html#form-element-pointer) which is involved in parsing start and end `<form>` tags:

> A start tag whose tag name is "form"
> If the form element pointer is not null, and there is no template element on the stack of open elements, then this is a parse error; ignore the token.
> 
> ...
> 
> set the form element pointer to point to the element created.

> An end tag whose tag name is "form"
> 1. Let node be the element that the form element pointer is set to, or null if it is not set to an element.
>
> 2. Set the form element pointer to null.
>
> 3. If node is null or if the stack of open elements does not have node in scope, then this is a parse error; return and ignore the token.
>
> 4. Generate implied end tags.
>
> 5. If the current node is not node, then this is a parse error.
> 
> 6. Remove node from the stack of open elements.

According to these rules:

the outer `<form>` sets 'form element pointer' to be the outer form

the first inner `<form>` is ignored due to 'form element pointer' being set

the first inner closing `</form>` tag is ignored due to parse error on step 5 - current node (which seems to be the outer `label` because it's the innermost not yet closed tag - there's no 'implied end tag generation' for labels) is not the same as 'form element pointer', but before that, the 'form element pointer' is set to null on step 2 

so the second inner form is preserved

**Comment by fb55** [comment]
@fictitious Thanks a lot for the great summary!
