### ISSUE TITLE
The value of nodeName in createElement

### ISSUE THREAD

**Issue by mike820324** [inikulin/parse5#60]
Hello,
Currently using this library to parse many websites, works really great. When looking at the source code, there is one thing that interested me.
https://github.com/inikulin/parse5/blob/master/lib/tree_adapters/default.js#L22

I'm just curious about why the ```nodeName``` value of ```createElement()``` is ```tagName``` instead of  ```"#element"```. 
- createDocument : ```nodeName = "#document"```
- createCommentNode: ```nodeName = "#comment"```
- createTextNode: ```nodeName = "#text"```
- createElement: ```nodeName = tagName```

Is there any particular reason not assigning ```"#element"``` to ```nodeName```?

**Comment by inikulin** [comment]
Hi, thank you for the kind words.

 parse5's tree formats are far from the real DOM (but can they be used to build one, see [jsdom ](https://github.com/tmpvar/jsdom)). However, I've tried to avoid adding new semantics to the well-known element properties, that's why `nodeName` is done in conformance with the [DOM spec](https://dom.spec.whatwg.org/#dom-node-nodename)

**Comment by mike820324** [comment]
I misunderstood the nodeName at the first place.  I thought it is the nodeType in the Node interface. :P
The link is very helpful. thanks for the quick reply and reference.
