### ISSUE TITLE
remove decodeHtmlEntities

### ISSUE THREAD

**Issue by stevenvachon** [inikulin/parse5#75]
Per the discussion in #72, I think it would make most sense to remove this option and replace it with information in documentation (#63). Someone wanting the option to not decode entities can choose to manually re-encode them on text nodes and attribute values.

**Comment by inikulin** [comment]
I have these thoughts for a long time. The only thing that stops me: for some reason we've implemented it and the worst part is what I couldn't figure out why we did it.  The origin of all this is in the #31 and after re-reading the only argument for this feature that I can find is: "it would be cool" . Now I have no idea why I decided to add this option, so let's just pretend I was deadly drunk at the time :beer: 

The points that bothers me:
 * Those things are dangerous and inconsistent with spec, e.g.: https://github.com/inikulin/parse5/pull/74#issuecomment-144431330
 * I can't figure out a real life scenario for this options.

So, I'll keep this issue in the proposal state for a week or so to see if anyone will come up and argue for this feature. Otherwise, it will be removed from the v2.0 (MUAHAHHAHAHA :smiling_imp:)

**Comment by inikulin** [comment]
I guess the best solution will be to ask guys who participated in the original suggestion and figure out their scenario and possible workaround: \cc @alanclarke @pdpi @winhamwr

**Comment by stevenvachon** [comment]
I had thought it useful for whitespace normalization, where entities in the original text would not contribute to the concept of "multiple spaces".

**Comment by alanclarke** [comment]
reason we did this is because it makes lossy and potentially breaking changes to the input. e.g. urls get corrupted:
```
<a href="http://example.com?hello=1&world=2"></a>
becomes:
<a href="http://example.com?hello=1&amp;world=2"></a>
```
which is not equivalent

**Comment by alanclarke** [comment]
sorry for only seeing this now btw!

**Comment by stevenvachon** [comment]
@alanclarke but that should not be a global flag, but perhaps a feature specifically hardcoded to url attributes.

**Comment by alanclarke** [comment]
@stevenvachon consider the following case:

<img width="335" alt="screenshot 2015-11-02 21 20 16" src="https://cloud.githubusercontent.com/assets/640611/10894627/bd45aeac-81a7-11e5-82c9-8cab9a2d1824.png">

you can see from the above that really neither strategy will truly replicate the browser behaviour, that's why its useful to provide users with the ability to opt out of potential side effects like that

**Comment by stevenvachon** [comment]
@alanclarke seems to me that resolving the entities will produce a consistently valid url in the output tree. It is always possible to re-enode them if you want to produce valid xhtml.

**Comment by alanclarke** [comment]
@stevenvachon but we'd need a parser to know which to re-encode?

**Comment by stevenvachon** [comment]
@alanclarke wouldn't that be the responsibility of the application using the parser? The DOM (or jsdom) decides when to re-encode.

**Comment by inikulin** [comment]
@alanclarke Thank you for the clarification. 

> you can see from the above that really neither strategy will truly replicate the browser behaviour, that's why its useful to provide users with the ability to opt out of potential side effects like that

But parse5 currently behaves the same way without flags and even without DOM implementation:
```js
> a.href = "http://blah.com/?a=b&c=d"
> a.href
```
This is the same as if you parse some markup and then change some attribute value in the resulting AST. It will remain unmodified.

```js
> a.outerHTML
```
This is the same as serialization of the given node, it will give you the same encoded result as in the browser.

So, I don't see any difference here.

**Comment by alanclarke** [comment]
it breaks reactjs for example:

https://github.com/inikulin/whacko/pull/15

**Comment by inikulin** [comment]
I don't get it. If you parse
```html
 <div data-react-props="{&quot;count&quot;:0}" />
```
it will be parsed as:
```js
 {"count":0}
```

But if you serialize it back with parse5, you will get:
```html
 <div data-react-props="{&quot;count&quot;:0}" />
```

So what is the problem here?

**Comment by MarkPieszak** [comment]
@alanclarke Long time coming, but updating from `1.5.1` and we've always been using `encodeHtmlEntities : false` when passing into the `serializer`. 

I'm trying to look through parse5 to see how this could be achieved now that it has been removed in 2.0, can anyone point me in the right direction? It's breaking now at `str.replace()` inside of the escapeString() function.

https://github.com/inikulin/parse5/blob/600449c7404408e0539fc0fd7a81050ae548a658/lib/serializer/index.js#L45

**Comment by inikulin** [comment]
>  It's breaking now at str.replace() inside of the escapeString() function.

It's unlikely the cause of this issue. Regarding disabled decoding can you explain your scenario in details?
