### ISSUE TITLE
Things that are awkward in jsdom right now in 1.5

### ISSUE THREAD

**Issue by domenic** [inikulin/parse5#78]
I wanted to note the things that are weird in jsdom right now that parse5 could help us with. I expect many of these are addressed in 2.0, or maybe even already addressed in 1.5 if we use the parse5 API instead of the htmlparser2 tree adapter. But I wanted to confirm with you.

### `<template>` serialization

We use parse5 for serialization. Serializing `<template>` requires serializing its contents. Currently parse5 does `treeAdapter.getChildNodes(node)[0]` and assumes that that will give the "template contents" document fragment. This causes jsdom to implement `treeAdapter.getChildNodes` as:

```js
exports.getChildNodes = function (node) {
  // parse5 treats template elements specially, assuming you return an array whose single item is the document fragment
  return node._templateContents ? [node._templateContents] : node.childNodes;
};
```

It would be better to have a dedicated `getTemplateContents` function that is only used for templates.

### `<template>` parsing

Similarly, `<template>`s are being handled specially in parsing. It appears that when parsing documents containing `<template>`, parse5 has a new `'#root'` node surrounding the template contents. When we encounter that, we need to take all of the root node's parse5 children, convert them to jsdom-children, and jsdom-insert them into the current "parent", which is a jsdom-template.

As a separate case, when parsing children of a `<template>` context using parseFragment, we need to note that case specially, and jsdom-insert the resulting jsdom-children into the jsdom-context node's template contents, instead of directly into the jsdom-context node.

It would be better if there were something matching ["appropriate place for inserting a node"](https://html.spec.whatwg.org/multipage/syntax.html#appropriate-place-for-inserting-a-node) more closely, which could use the `treeAdapter.getTemplateContents` somehow. Then parse5 could do all the work of figuring out where to place template children for us.

My suggestion here is a bit hazy as I'm not sure how, in an ideal world, jsdom should be interacting with parse5. Its current [`setChild` abstraction](https://github.com/tmpvar/jsdom/blob/f84265df9f83aa3ed9d7ee59ba5d54c65de5b080/lib/jsdom/browser/htmltodom.js#L115) seems a bit strange.

### Attributes

Currently we get attributes as an object map of local names -> values, plus two other maps of x-attribsPrefix and x-attribsNamespace. I'd prefer an (ordered) array of `{ localName, prefix, namespace }`.

**Comment by inikulin** [comment]
> It would be better to have a dedicated getTemplateContents function that is only used for templates.

Makes sense.

> Similarly, `<template>`s are being handled specially in parsing. It appears that when parsing documents containing `<template>`, parse5 has a new '#root' node surrounding the template contents. When we encounter that, we need to take all of the root node's parse5 children, convert them to jsdom-children, and jsdom-insert them into the current "parent", which is a jsdom-template.


parse5 uses `DocumentFragment` as the template `content`: https://github.com/inikulin/parse5/blob/master/lib/parser/index.js#L559. 
This is [per spec](https://html.spec.whatwg.org/multipage/scripting.html#template-contents). 

 Then, on insertion, we precisely follow ["appropriate place for inserting a node"](https://html.spec.whatwg.org/multipage/syntax.html#appropriate-place-for-inserting-a-node):
https://github.com/inikulin/parse5/blob/master/lib/parser/index.js#L534

 If I get it right, the issue is caused by the fact that in htmlparser2 tree format both `Document` and `DocumentFragment` have the same node type: https://github.com/inikulin/parse5/blob/master/lib/tree_adapters/htmlparser2.js#L64. 

Seems like the problem is with the htmlparser2 tree format, maybe the best solution will be to step away from it and implement custom tree adapter for the jsdom?

> Currently we get attributes as an object map of local names -> values, plus two other maps of x-attribsPrefix and x-attribsNamespace. I'd prefer an (ordered) array of { localName, prefix, namespace }.

Again, this is htmlparser2 legacy. htmlparser2 doesn't have attribute namespaces and prefixes implemented, and attributes collection there is a dictionary. That's why we need additional dictionaries for the namespaces and prefixes. Meanwhile, default adapter stores attributes the way they are provided by parser: https://github.com/inikulin/parse5/blob/master/lib/tree_adapters/default.js#L65. Which is array of `{name, value, prefix, namespace}` objects. So, again, it's one more reason to step away from the htmlparser2 tree adapter.

**Comment by inikulin** [comment]
Oh, I've missed that:
> As a separate case, when parsing children of a `<template>` context using parseFragment, we need to note that case specially, and jsdom-insert the resulting jsdom-children into the jsdom-context node's template contents, instead of directly into the jsdom-context node.

> It would be better if there were something matching "appropriate place for inserting a node" more closely, which could use the treeAdapter.getTemplateContents somehow. Then parse5 could do all the work of figuring out where to place template children for us.


I'm afraid I don't get it. According to the spec, fragment parsing algorithm shouldn't perform insertion into the context element. It should just return `documentFragment` with the parsed content. The content insertion strategy is up to the parser adopters.

Let's summarize: the only thing that I can do here for you is provide `getTemplateContents` and `createTemplateContents` methods. In that case template content creation will be up to the tree adapter implementer, but the spec clearly [says](https://html.spec.whatwg.org/multipage/scripting.html#template-contents) that template content should be the `documentFragment`.  It bothers me, because implementer could break the spec in that case.
\cc @domenic

**Comment by inikulin** [comment]
...or, I can implement `setTemplateContent (tmpl, contentFragment)` instead of `createTemplateContents`. Will it address your issues then?

**Comment by domenic** [comment]
> ...or, I can implement setTemplateContent (tmpl, contentFragment)

I think this is the thing that makes the most sense. (Once we fix our other issues by using the parse5 tree adapter instead of the htmlparser2 one.) For parsing, the adapter needs a tree construction method that is aware of the fact that "appropriate place for inserting a node" sometimes requires something more complicated than appendChild(). Just like how for serialization, it needs a tree reading method that is aware that sometimes the children to serialize are more complicated than just getChildNodes().

BTW I noticed that adapter.appendChild is not documented in https://github.com/inikulin/parse5/blob/master/docs/05_api_reference.md#TreeAdapter. I guess that is still in progress :).

**Comment by inikulin** [comment]
@domenic Great, let's do it this way then.

> BTW I noticed that adapter.appendChild is not documented in https://github.com/inikulin/parse5/blob/master/docs/05_api_reference.md#TreeAdapter. I guess that is still in progress :).

Thanks for pointing this out. Actually, I've missed it =)

**Comment by stevenvachon** [comment]
I think a similar thing is happening with non-javascript type script elements:
```js
parse5.parseFragment('<script type="text/foo"><tag attr/></script:');
```
The contents should be a string, correct? `<tag>` is being parsed as HTML.

**Comment by stevenvachon** [comment]
@inikulin ^^
