### ISSUE TITLE
Quirks Mode

### ISSUE THREAD

**Issue by Sebmaster** [inikulin/parse5#83]
Currently trying to switch jsdom to 2.0 and want to implement parsing with our own document adapter. Two issues I've come across there:

* It seems like parse5 makes no differentiation between quirks- and limited-quirks mode? Intended? The `document.backCompat` property should actually handle limited-quirks as no-quirks, but I'm not sure if other web platform APIs require the more fine-grained differentiation. Possible to change?
* I think it's missing the XHTML doctypes (`-//W3C//DTD XHTML 1.0 Frameset//`and `-//W3C//DTD XHTML 1.0 Transitional//`) (they're both described in the [html parser](https://html.spec.whatwg.org/multipage/syntax.html#the-initial-insertion-mode)).

**Comment by inikulin** [comment]
@Sebmaster As far as I remember it was intended. A the time it was written parse5 was not planned for use in the full-featured DOM implementation and unlike quirks-mode limited-quirks doesn't affect parsing algorithm. So it was just removed, because it's looked unnecessary. 

> Possible to change?
Yes, I'll try to take my hands on it somewhere around next week.

**Comment by inikulin** [comment]
JFYI this will require introduction of the new method to the tree adapters and hence major version bump. I'm waiting for the feedback from @Sebmaster regarding scripting. So if it require any additional breaking changes, I'll be able implement them in the bunch.
