### ISSUE TITLE
browserify fails for parse5

### ISSUE THREAD

**Issue by EricJergensen** [inikulin/parse5#875]
main.js: const SAXParser = require('parse5-sax-parser');

browserify main.js -p esmify -o sax-parser.js
Error: Can't walk dependency graph: ENOENT: no such file or directory, lstat '/private/tmp/p5/node:stream'
    required by /private/tmp/p5/node_modules/parse5-sax-parser/dist/index.js

For context, target application is to use the sax-parse in a Service Worker (on a ReadableStream from a response body).

This may be more a request for documentation improvement because the FAQ says just use browserify without any details.

**Comment by fb55** [comment]
`parse5-sax-parser` uses Node's `stream` module, which isn't available in browsers. Browserify would include the `stream` module in the output,  but doesn't seem to support `node:` protocol imports, which is breaking things for you. 

More modern build tooks like Webpack are probably the better choice for you herem but getting everthing set up so that node's native modules are included will still be annoying to do. If you can use only the main `parse5` module, that would make things easier for you.
